name: Build DLL

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build DLL
      run: msbuild YimMenuDLL.vcxproj /p:Configuration=Release

    - name: Upload DLL
      uses: actions/upload-artifact@v2
      with:
        name: YimMenuDLL
        path: x64/Release/YimMenuDLL.dll
